### ISSUE TITLE
Codecast next recording dosen't work

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#106]
After the recording is done, after clicking the save button, nothing appears... See the video:
https://youtu.be/iAXRN4KE_S4

voici l'erreur dans la console:

```

index.js:46 action {type: "Save.Prepare.Start"}
index.js:46 action {type: "Save.Prepare.Pending", @@redux-saga/SAGA_ACTION: true}
index.js:46 action {type: "Save.Prepare.Completed", @@redux-saga/SAGA_ACTION: true}
index.js:46 action {type: "Save.Events.Upload.Pending", @@redux-saga/SAGA_ACTION: true}
index.js:46 action {type: "Save.Events.Upload.Success", url: "https://fioi-recordings.s3.amazonaws.com/guest/1526564850926.json", @@redux-saga/SAGA_ACTION: true}
index.js:46 action {type: "Save.Audio.Upload.Pending", @@redux-saga/SAGA_ACTION: true}
index.js:46 action {type: "Save.Audio.Upload.Success", url: "https://fioi-recordings.s3.amazonaws.com/guest/1526564850926.mp3", @@redux-saga/SAGA_ACTION: true}
index.js:46 action {type: "Save.Success", playerUrl: "https://codecast.france-ioi.org/next/player?base=h…cordings.s3.amazonaws.com%2Fguest%2F1526564850926", @@redux-saga/SAGA_ACTION: true}
save_screen.js:138 Uncaught ReferenceError: Intents is not defined
    at SaveScreen.render (save_screen.js:138)
    at finishClassComponent (react-dom.development.js:8377)
    at updateClassComponent (react-dom.development.js:8345)
    at beginWork (react-dom.development.js:8966)
    at performUnitOfWork (react-dom.development.js:11798)
    at workLoop (react-dom.development.js:11827)
    at HTMLUnknownElement.callCallback (react-dom.development.js:104)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:142)
    at invokeGuardedCallback (react-dom.development.js:191)
    at replayUnitOfWork (react-dom.development.js:11302)
render @ save_screen.js:138
finishClassComponent @ react-dom.development.js:8377
updateClassComponent @ react-dom.development.js:8345
beginWork @ react-dom.development.js:8966
performUnitOfWork @ react-dom.development.js:11798
workLoop @ react-dom.development.js:11827
callCallback @ react-dom.development.js:104
invokeGuardedCallbackDev @ react-dom.development.js:142
invokeGuardedCallback @ react-dom.development.js:191
replayUnitOfWork @ react-dom.development.js:11302
renderRoot @ react-dom.development.js:11869
performWorkOnRoot @ react-dom.development.js:12422
performWork @ react-dom.development.js:12343
performSyncWork @ react-dom.development.js:12320
requestWork @ react-dom.development.js:12220
scheduleWorkImpl @ react-dom.development.js:12095
scheduleWork @ react-dom.development.js:12055
enqueueSetState @ react-dom.development.js:6632
Component.setState @ react.development.js:242
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
dispatch @ createStore.js:173
(anonymous) @ middleware.js:66
dispatch @ applyMiddleware.js:35
(anonymous) @ utils.js:250
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
runSelectEffect @ proc.js:699
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
runSelectEffect @ proc.js:699
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
value @ save_screen.js:120
callCallback @ react-dom.development.js:104
invokeGuardedCallbackDev @ react-dom.development.js:142
invokeGuardedCallback @ react-dom.development.js:191
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:205
executeDispatch @ react-dom.development.js:470
executeDispatchesInOrder @ react-dom.development.js:492
executeDispatchesAndRelease @ react-dom.development.js:590
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:601
forEachAccumulated @ react-dom.development.js:571
runEventsInBatch @ react-dom.development.js:732
runExtractedEventsInBatch @ react-dom.development.js:741
handleTopLevel @ react-dom.development.js:4198
batchedUpdates @ react-dom.development.js:12510
batchedUpdates @ react-dom.development.js:1943
dispatchEvent @ react-dom.development.js:4279
interactiveUpdates @ react-dom.development.js:12565
interactiveUpdates @ react-dom.development.js:1962
dispatchInteractiveEvent @ react-dom.development.js:4256
react-dom.development.js:9627 The above error occurred in the <SaveScreen> component:
    in SaveScreen (created by View(SaveScreen))
    in View(SaveScreen) (created by RecorderApp)
    in div (created by RecorderApp)
    in RecorderApp (created by View(RecorderApp))
    in View(RecorderApp)
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:9627
logError @ react-dom.development.js:9666
commitErrorLogging @ react-dom.development.js:9879
commitAllLifeCycles @ react-dom.development.js:11443
callCallback @ react-dom.development.js:104
invokeGuardedCallbackDev @ react-dom.development.js:142
invokeGuardedCallback @ react-dom.development.js:191
commitRoot @ react-dom.development.js:11578
completeRoot @ react-dom.development.js:12475
performWorkOnRoot @ react-dom.development.js:12425
performWork @ react-dom.development.js:12343
performSyncWork @ react-dom.development.js:12320
requestWork @ react-dom.development.js:12220
scheduleWorkImpl @ react-dom.development.js:12095
scheduleWork @ react-dom.development.js:12055
enqueueSetState @ react-dom.development.js:6632
Component.setState @ react.development.js:242
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
dispatch @ createStore.js:173
(anonymous) @ middleware.js:66
dispatch @ applyMiddleware.js:35
(anonymous) @ utils.js:250
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:486
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
Promise.then (async)
resolvePromise @ proc.js:450
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
runSelectEffect @ proc.js:699
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
runSelectEffect @ proc.js:699
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
value @ save_screen.js:120
callCallback @ react-dom.development.js:104
invokeGuardedCallbackDev @ react-dom.development.js:142
invokeGuardedCallback @ react-dom.development.js:191
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:205
executeDispatch @ react-dom.development.js:470
executeDispatchesInOrder @ react-dom.development.js:492
executeDispatchesAndRelease @ react-dom.development.js:590
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:601
forEachAccumulated @ react-dom.development.js:571
runEventsInBatch @ react-dom.development.js:732
runExtractedEventsInBatch @ react-dom.development.js:741
handleTopLevel @ react-dom.development.js:4198
batchedUpdates @ react-dom.development.js:12510
batchedUpdates @ react-dom.development.js:1943
dispatchEvent @ react-dom.development.js:4279
interactiveUpdates @ react-dom.development.js:12565
interactiveUpdates @ react-dom.development.js:1962
dispatchInteractiveEvent @ react-dom.development.js:4256
utils.js:225 uncaught at uploadRecording ReferenceError: Intents is not defined
    at SaveScreen.render (https://codecast.france-ioi.org/next/build/index.js:1380:27)
    at finishClassComponent (https://codecast.france-ioi.org/next/build/vendor.js:65149:33)
    at updateClassComponent (https://codecast.france-ioi.org/next/build/vendor.js:65117:12)
    at beginWork (https://codecast.france-ioi.org/next/build/vendor.js:65738:16)
    at performUnitOfWork (https://codecast.france-ioi.org/next/build/vendor.js:68570:16)
    at workLoop (https://codecast.france-ioi.org/next/build/vendor.js:68599:26)
    at renderRoot (https://codecast.france-ioi.org/next/build/vendor.js:68630:9)
    at performWorkOnRoot (https://codecast.france-ioi.org/next/build/vendor.js:69194:24)
    at performWork (https://codecast.france-ioi.org/next/build/vendor.js:69115:9)
    at performSyncWork (https://codecast.france-ioi.org/next/build/vendor.js:69092:5)
```

**Comment by epixode** [comment]
Thanks, I just fixed this on /next.

You will notice that the interface while saving looks weird (it is still useable).  It will soon be replaced by a better version showing progress both on the encoding and upload steps.
